### ISSUE TITLE
error

### ISSUE THREAD

**Issue by arunwuhan** [zhangxiaochen95/cross_layer_opt_with_grl#2]
When I run the exp_queue.py, these errors are thrown：Traceback (most recent call last):
  File "D:\githubcode\failed\cross_layer_opt_with_grl\exp_queue.py", line 1, in <module>
    from run import *
  File "D:\githubcode\failed\cross_layer_opt_with_grl\run.py", line 18, in <module>
    from envs import REGISTRY as env_REGISTRY
  File "D:\githubcode\failed\cross_layer_opt_with_grl\envs\__init__.py", line 3, in <module>
    from envs.multi_ubs_coverage.multi_ubs_coverage import MultiUbsCoverageEnv
ModuleNotFoundError: No module named 'envs.multi_ubs_coverage'

**Comment by arunwuhan** [comment]
do you have weixin？ my vx：ar15827394769，I have  some problem with this code,I would appreciate it if you could help me

**Comment by kazuha-ui** [comment]
I encounter the same error as you did.Did you find the solution?

**Comment by arunwuhan** [comment]
> I encounter the same error as you did.Did you find the solution?

no，It may be that there is a problem with my environment configuration, but I don't know how to do it

**Comment by zhangxiaochen95** [comment]
I have checked the code, it contains `import` of removed environments (which are unrelated to this paper).

**Comment by zhangxiaochen95** [comment]
I checked the code and find that it contains import of removed environments (which are unrelated to this paper). Sorry for the error. These unused codes have been removed.
